language: node_js

node_js:
  - "0.10"
  - "0.12"
  - "4.2"
  - "5.0"

# Use container-based Travis infrastructure.
sudo: false

branches:
  only:
    - master

env:
  matrix:
    - NPM_3=true
    - NPM_3=false

before_install:
  # GUI for real browsers.
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

  # Potentially update to npm 3
  - 'if [ "$NPM_3" = true ]; then npm install -g npm@3; else true; fi'

script:
  - npm --version
  - node_modules/.bin/builder run check-ci

  # Prune deps to just production and ensure we can still build
  - npm prune --production
  - node_modules/.bin/builder run build
